/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fomularios;
import Academico.*;
import javax.swing.JOptionPane;

/**
 *
 * @author JHP
 */
public class frmAsignatura extends javax.swing.JFrame {

    /**
     * Creates new form frmAsignatura
     */
    public frmAsignatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblRequisitos = new javax.swing.JLabel();
        lblPlanEstudio = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        txtRequisitos = new javax.swing.JTextField();
        txtPlanEstudio = new javax.swing.JTextField();
        btnGuiar = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        btnInstruir = new javax.swing.JButton();
        btnAgrupar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCodigo.setText("Codigo");

        lblDuracion.setText("Duracion");

        lblHorario.setText("Horario");

        lblRequisitos.setText("Requisitos");

        lblPlanEstudio.setText("Plan de Estudio");

        btnGuiar.setText("Guiar()");
        btnGuiar.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnGuiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiarActionPerformed(evt);
            }
        });

        btnAsignar.setText("Asignar()");
        btnAsignar.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnInstruir.setText("Instruir()");
        btnInstruir.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnInstruir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruirActionPerformed(evt);
            }
        });

        btnAgrupar.setText("Agrupar()");
        btnAgrupar.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnAgrupar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgruparActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(lblDuracion)
                            .addComponent(lblHorario)
                            .addComponent(lblRequisitos)
                            .addComponent(lblPlanEstudio))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPlanEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRequisitos, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAsignar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInstruir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgrupar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnRegistrar)
                        .addGap(49, 49, 49)
                        .addComponent(btnMostrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuracion)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorario)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRequisitos)
                    .addComponent(txtRequisitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlanEstudio)
                    .addComponent(txtPlanEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnMostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuiar)
                    .addComponent(btnAsignar)
                    .addComponent(btnInstruir)
                    .addComponent(btnAgrupar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static Asignatura asignatura = new Asignatura();
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String codigo = txtCodigo.getText().toString();
        String horario = txtHorario.getText().toString();
        String requisitos = txtRequisitos.getText().toString();
        String planestudio = txtPlanEstudio.getText().toString();
        int duracion = Integer.parseInt(txtDuracion.getText().toString());

        //enviar
        asignatura.setCodigo(codigo);
        asignatura.setDuracion(duracion);
        asignatura.setHorario(horario);
        asignatura.setPlanestudio(planestudio);
        asignatura.setRequisitos(requisitos);
        
        //mensaje de verificaicon correcta
        JOptionPane.showMessageDialog(rootPane, "se registro correctamente");
        
        //limpiar la caja de texto
        txtCodigo.setText("");
        txtHorario.setText("");
        txtRequisitos.setText("");
        txtPlanEstudio.setText("");
        txtDuracion.setText("");
        txtCodigo.setText("");
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        String codigo = asignatura.getCodigo();
        String horario = asignatura.getHorario();
        String requisitos = asignatura.getRequisitos();
        String planestudio = asignatura.getPlanestudio();
        int duracion = asignatura.getDuracion();
        JOptionPane.showMessageDialog(rootPane, "Codigo: "+codigo+" Horario: "+ horario+" Requisitos: "+requisitos+" Plan de Estudio: "+ 
                planestudio+" Duración: "+ duracion);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGuiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiarActionPerformed
        JOptionPane.showMessageDialog(rootPane,asignatura.Guiar().toString());
    }//GEN-LAST:event_btnGuiarActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        JOptionPane.showMessageDialog(rootPane,asignatura.Asignar().toString());
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnInstruirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruirActionPerformed
        JOptionPane.showMessageDialog(rootPane,asignatura.Instruir().toString());
    }//GEN-LAST:event_btnInstruirActionPerformed

    private void btnAgruparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgruparActionPerformed
        JOptionPane.showMessageDialog(rootPane,asignatura.Agrupar().toString());
    }//GEN-LAST:event_btnAgruparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAsignatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrupar;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnGuiar;
    private javax.swing.JButton btnInstruir;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblPlanEstudio;
    private javax.swing.JLabel lblRequisitos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtPlanEstudio;
    private javax.swing.JTextField txtRequisitos;
    // End of variables declaration//GEN-END:variables
}
