/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fomularios;

/**
 *
 * @author JHP
 */
public class frmNotas extends javax.swing.JFrame {

    /**
     * Creates new form frmnotas
     */
    public frmNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAF = new javax.swing.JLabel();
        lblINF = new javax.swing.JLabel();
        lblRS = new javax.swing.JLabel();
        lblAporte1 = new javax.swing.JLabel();
        lblAporte2 = new javax.swing.JLabel();
        lblAporte3 = new javax.swing.JLabel();
        lblNotaFi = new javax.swing.JLabel();
        btnAprobar = new javax.swing.JButton();
        btnDesaprobar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        txtAF = new javax.swing.JTextField();
        txtINF = new javax.swing.JTextField();
        txtRS = new javax.swing.JTextField();
        txtAporte1 = new javax.swing.JTextField();
        txtAporte2 = new javax.swing.JTextField();
        txtAporte3 = new javax.swing.JTextField();
        txtNotaFi = new javax.swing.JTextField();
        btnRegistrarAP1 = new javax.swing.JButton();
        btnRegistrarAP2 = new javax.swing.JButton();
        btnRegistrarAP3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAF.setText("AF");

        lblINF.setText("INF");

        lblRS.setText("RS");

        lblAporte1.setText("Aporte 1");

        lblAporte2.setText("Aporte 2");

        lblAporte3.setText("Aporte 3");

        lblNotaFi.setText("Nota Final");

        btnAprobar.setText("Aprobar ()");
        btnAprobar.setMargin(new java.awt.Insets(2, 10, 2, 10));

        btnDesaprobar.setText("Desaprobar ()");
        btnDesaprobar.setMargin(new java.awt.Insets(2, 10, 2, 10));

        btnRegistrar.setText("Registrar ()");
        btnRegistrar.setMargin(new java.awt.Insets(2, 10, 2, 10));

        btnMostrar.setText("Mostrar ()");
        btnMostrar.setMargin(new java.awt.Insets(2, 10, 2, 10));

        btnRegistrarAP1.setText("RegistrarAP1");

        btnRegistrarAP2.setText("RegistrarAP2");

        btnRegistrarAP3.setText("RegistrarAP3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 83, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAprobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDesaprobar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAF)
                            .addComponent(lblINF)
                            .addComponent(lblRS)
                            .addComponent(lblAporte1)
                            .addComponent(lblAporte2)
                            .addComponent(lblAporte3)
                            .addComponent(lblNotaFi))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtINF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAporte1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAporte2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAporte3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNotaFi)
                            .addComponent(txtAF))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarAP1)
                    .addComponent(btnRegistrarAP2)
                    .addComponent(btnRegistrarAP3))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAF)
                    .addComponent(txtAF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblINF)
                    .addComponent(txtINF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRS)
                    .addComponent(txtRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAporte1)
                    .addComponent(txtAporte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarAP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAporte2)
                    .addComponent(txtAporte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarAP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAporte3)
                    .addComponent(txtAporte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarAP3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotaFi)
                    .addComponent(txtNotaFi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAprobar)
                    .addComponent(btnRegistrar))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar)
                    .addComponent(btnDesaprobar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprobar;
    private javax.swing.JButton btnDesaprobar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarAP1;
    private javax.swing.JButton btnRegistrarAP2;
    private javax.swing.JButton btnRegistrarAP3;
    private javax.swing.JLabel lblAF;
    private javax.swing.JLabel lblAporte1;
    private javax.swing.JLabel lblAporte2;
    private javax.swing.JLabel lblAporte3;
    private javax.swing.JLabel lblINF;
    private javax.swing.JLabel lblNotaFi;
    private javax.swing.JLabel lblRS;
    private javax.swing.JTextField txtAF;
    private javax.swing.JTextField txtAporte1;
    private javax.swing.JTextField txtAporte2;
    private javax.swing.JTextField txtAporte3;
    private javax.swing.JTextField txtINF;
    private javax.swing.JTextField txtNotaFi;
    private javax.swing.JTextField txtRS;
    // End of variables declaration//GEN-END:variables
}
